/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface RingComponent {
    }
}
declare global {
    interface HTMLRingComponentElement extends Components.RingComponent, HTMLStencilElement {
    }
    var HTMLRingComponentElement: {
        prototype: HTMLRingComponentElement;
        new (): HTMLRingComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ring-component": HTMLRingComponentElement;
    }
}
declare namespace LocalJSX {
    interface RingComponent {
    }
    interface IntrinsicElements {
        "ring-component": RingComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ring-component": LocalJSX.RingComponent & JSXBase.HTMLAttributes<HTMLRingComponentElement>;
        }
    }
}
